name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2  # Updated to the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Verify AWS credentials
        run: aws sts get-caller-identity  # Optional: Verifies AWS credentials are correctly configured

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://devops-port --delete

